name: Trigger Build
on:
  push:
    branches: [ "main" ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build in infra repo
        run: |
          curl -X POST \
            -H "Authorization: Bearer 0e970c75ab2772af8d694400c3efbab7d91ce10d" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/shahryaraly/project-rc-infra/dispatches \
            -d '{"event_type":"trigger_build"}'
