name: Trigger Build
on:
  push:
    branches: [ "main" ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build in infra repo
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.INFRA_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/shahryaraly/project-rc-infra/actions/workflows/build-push.yaml/dispatches \
            -d '{"ref": "main","inputs": {"application_repo":"demo-cicd"}}'
